name = "Geodesics"
uuid = "a2e5014b-b75e-4350-99f8-e3332a06fb8b"
authors = ["David Radice <david.radice@psu.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
